### ISSUE TITLE
Feature Request: Append a custom message to all errors.

### ISSUE THREAD

**Issue by TechDufus** [kubewarden/policy-server#828] opened 2024-07-17 14:35 UTC
### Is your feature request related to a problem?

It would be a very convenient thing for us to add a custom "wrapper" message to all errors returned by the k8s api (via the policy server).

### Solution you'd like

For example, Adding something like the following to all errors: "<some policy error>. This error was generated by Kubewarden. Please view more details about this here: <some link to internal company documentation>"

Being able to let this at the policy server level is probably where I see this happening, but feel free to correct me. This helps us create a 'funnel' for our many users to hit some self-help docs, and let them know the error is known and there's internal company help for them, instead of trying to scour the interwebs first.

**Comment by flavio** [comment] 2024-07-17 14:37
Duplicate of https://github.com/kubewarden/kubewarden-controller/issues/655

**Closed by flavio** 2024-07-17 14:37 UTC
